languageCode = "en-us"
title = "Bomberry.com"
theme = "bomberry"
# theme = "academic"
# layoutDir = "themes"
metaDataFormat = "toml"

# canonifyurls = true
baseURL = "/"
casestudy_asset_path = "/portfolio/assets/"

date_format = "Jan 2, 2006"
time_format = "3:04 PM"


[params]
  copyright = "Copyright &copy; {year} Kevin Bomberry. All rights reserved. All other &copy;&nbsp;&#124;&nbsp;&reg;&nbsp;&#124;&nbsp;&trade; rights reserved by original holders respectively."
  copyrightHTMLA = "Copyright &#xA9; 2018 Kevin Bomberry. All Rights Reserved."
  copyrightHTML = "Copyright &#xA9; 2018 Kevin Bomberry. All rights reserved. All other &copy;&nbsp;&#124;&nbsp;&reg;&nbsp;&#124;&nbsp;&trade; rights reserved by original holders respectivly."
  TwitterUser = "bomberry"

  includeFileInfo = false
  includeHugoMeta = false

  my_name = "Kevin Bomberry"
  my_title = "Product, Interaction, and Experience Designer"
  my_contact_email = "kevin+contact@bomberry.com"
  my_email = "kevin+contact@bomberry.com"

  #   (relative to /static/css and /static/js respectively)
  custom_fonts = []
  custom_css = []
  custom_js  = []



  # Configuration of resume pages.
  [params.resume]
    # Show talk time?
    show_details = false

  # Configuration of casestudies pages.
  [params.casestudies]
    # Show talk time?
    reading_time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3


  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:kevin+contact@bomberry.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/kevinbomberry"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/bomberry"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/bomberry"


  client_logos = ["adobe", "ideo", "microsoft", "stanford", "streamlio", "vlab"]

  [[params.client_logo]]
    imgage = "adobe"
    format = "png"
    style = "medium"
  [[params.client_logo]]
    imgage = "ideo"
    format = "png"
    style = "medium"
  [[params.client_logo]]
    imgage = "microsoft"
    format = "png"
    style = "medium"
  [[params.client_logo]]
    imgage = "stanford"
    format = "png"
    style = "medium"
  [[params.client_logo]]
    imgage = "streamlio"
    format = "png"
    style = "medium"
  [[params.client_logo]]
    imgage = "vlab"
    format = "png"
    style = "medium"

# [permalinks]
# 	page = "/:title/"
# 	about = "/:filename/"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[menu]
  # [[menu.main]]
  #   identifier = "news"
  #   name = "news"
  #   pre = "<i class='fa fa-bullhorn'></i>"
  #   url = "/news/"
  #   weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    pre = "<i class='fa fa-clipboard'></i>"
    # post = "</i>"
    url = "/resume/"
    weight = 20
    hidden = false

  [[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    pre = "<i class='fa fa-layer-group'> </i>"
    url = "/portfolio/"
    weight = 40
    hidden = false

#  [[menu.main]]
#    identifier = "kitchen"
#    name = "kitchen"
#    pre = "<i class='fa fa-coffee'> </i>"
#    url = "/kitchen/"
#    weight = 60
#    hidden = false

  # [[menu.main]]
  #   identifier = "1"
  #   name = "1"
  #   pre = "<i class='fa fa-heart'></i>"
  #   url = "/1/"
  #   weight = 80
  #   hidden = true

  # [[menu.main]]
  #   identifier = "projects"
  #   name = "projects"
  #   pre = "<i class='fa fa-paint-brush'></i>"
  #   url = "/projects/"
  #   weight = 100
  #   hidden = false

  # [[menu.main]]
  #   identifier = "articles"
  #   name = "articles"
  #   pre = "<i class='fa fa-book-reader'></i>"
  #   url = "/articles/"
  #   weight = 50
  #   hidden = true

  # [[menu.main]]
  #   identifier = "freebies"
  #   name = "freebies"
  #   pre = "<i class='fa fa-download'></i>"
  #   url = "/freebies/"
  #   weight = 60
  #   hidden = true

  [[menu.main]]
    identifier = "about"
    name = "about"
    pre = "<i class='fa fa-user'></i>"
    url = "/about/"
    weight = 110
    hidden = true

  # [[menu.main]]
  #   identifier = "contact"
  #   name = "contact"
  #   pre = "<i class='fa fa-bullhorn'></i>"
  #   url = "/contact/"
  #   weight = 120
  #   hidden = true

  # [[menu.main]]
  #   identifier = "adobe"
  #   name = "adobe"
  #   pre = "<i class='fa fa-'>A </i>"
  #   url = "/adobe/"
  #   weight = 140
  #   hidden = true

  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   url = "/posts"
  #   weight = 3

  [[menu.resume]]
    name = "Introduction"
    url = "#introduction"
    weight = 20

  [[menu.resume]]
    name = "Experience"
    url = "#experience"
    weight = 30

  [[menu.resume]]
    name = "Skills"
    url = "#skills"
    weight = 40

  [[menu.resume]]
    name = "Tools"
    url = "#tools"
    weight = 50

  [[menu.resume]]
    name = "Contact"
    url = "#contact"
    weight = 100



  [[menu.portfolio]]
    name = "Streamlio"
    url = "#streamlio"
    weight = 900


  [[menu.portfolio]]
    name = "CraftMaster"
    url = "#craftmaster"
    weight = 1000

  [[menu.portfolio]]
    name = "Auguste"
    url = "#adobe-auguste"
    weight = 1010

  [[menu.portfolio]]
    name = "Photoshop"
    url = "#adobe-photoshop"
    weight = 1020

  # [[menu.portfolio]]
  #   name = "Felix"
  #   url = "#felix"
  #   weight = 1030

  # [[menu.portfolio]]
  #   name = "Adobe"
  #   url = "#adobe"
  #   weight = 1040

  # [[menu.portfolio]]
  #   name = "Dimensions"
  #   url = "#dimensions"
  #   weight = 1050

  # [[menu.portfolio]]
  #   name = "Ps.com"
  #   url = "#PsCom"
  #   weight = 1060

  # [[menu.portfolio]]
  #   name = "PS Materials"
  #   url = "#materials"
  #   weight = 1070

  [[menu.portfolio]]
    name = "Able Pear"
    url = "#able-pear"
    weight = 1080

  # [[menu.portfolio]]
  #   name = "Artwork"
  #   url = "#artwork"
  #   weight = 1090


  [[menu.casestudy_streamlio]]
    name = "Introduction"
    url = "#introduction"
    weight = 1000
  [[menu.casestudy_streamlio]]
    name = "Branding"
    url = "#logo"
    weight = 2010
  [[menu.casestudy_streamlio]]
    name = "Web Site"
    url = "#sitestart"
    weight = 2030
  [[menu.casestudy_streamlio]]
    name = "Conclusion"
    url = "#result"
    weight = 3040


  [[menu.casestudy_auguste]]
    name = "Introduction"
    url = "#introduction"
    weight = 1000
  [[menu.casestudy_auguste]]
    name = "Planning"
    url = "#technology"
    weight = 2010
  [[menu.casestudy_auguste]]
    name = "App Design"
    url = "#wireframes"
    weight = 2030
  [[menu.casestudy_auguste]]
    name = "Conclusion"
    url = "#result"
    weight = 3040


  [[menu.casestudy_photoshop]]
    name = "Introduction"
    url = "#introduction"
    weight = 1000
  # [[menu.casestudy_photoshop]]
  #   name = "The Problem"
  #   url = "#problem"
  #   weight = 2000
  [[menu.casestudy_photoshop]]
    name = "Challenge 1"
    url = "#challenge1"
    weight = 2010
  [[menu.casestudy_photoshop]]
    name = "Challenge 2"
    url = "#challenge2"
    weight = 2020
  [[menu.casestudy_photoshop]]
    name = "Challenge 3"
    url = "#challenge3"
    weight = 2030
  [[menu.casestudy_photoshop]]
    name = "Conclusion"
    url = "#conclusion"
    weight = 3000


  [[menu.casestudy_craftmaster]]
    name = "Introduction"
    url = "#introduction"
    weight = 1000
  [[menu.casestudy_craftmaster]]
    name = "Branding"
    url = "#logo"
    weight = 2010
  [[menu.casestudy_craftmaster]]
    name = "App Design"
    url = "#appPlanning"
    weight = 2030
  [[menu.casestudy_craftmaster]]
    name = "Web Site"
    url = "#site"
    weight = 2040
  [[menu.casestudy_craftmaster]]
    name = "Conclusion"
    url = "#conclusion"
    weight = 3050




  [[menu.projects]]
    name = "Project ARIA"
    url = "#aria"
    weight = 1000

  [[menu.projects]]
    name = "Watch & Gears"
    url = "#watchAndGears"
    weight = 1010

  [[menu.projects]]
    name = "AppGraph Study"
    url = "#appGraph"
    weight = 1020

  [[menu.projects]]
    name = "Contextual UI"
    url = "#contextUI"
    weight = 1030





  [[menu.kitchen]]
    name = "Newsletter"
    url = "#newsletter"
    weight = 20

  [[menu.kitchen]]
    name = "Seasoning Salts"
    url = "#seasoningSalts"
    weight = 40

  [[menu.kitchen]]
    name = "Simple Syrups"
    url = "#simpleSyrup"
    weight = 60

  [[menu.kitchen]]
    name = "About"
    url = "#about"
    weight = 100




# Taxonomies.
# Turn off Taxonomy indexing by uncommenting the line below and commenting out the taxonomy lines
# disableKinds = ["taxonomy", "taxonomyTerm"]
[taxonomies]
  category = "categories"
  keyword = "keywords"
  tag = "tags"
  language = "languages"
  platform = "platforms"
  service = "services"
  tool = "tools"


# Sitemap Variables
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
