languageCode = "en-us"
title = "Bomberry.com"
theme = "bomberry"
# theme = "academic"
# layoutDir = "themes"
metaDataFormat = "toml"

# canonifyurls = true
baseURL = "/"
casestudy_asset_path = "/portfolio/assets/"

date_format = "Jan 2, 2006"
time_format = "3:04 PM"


[params]
  CopyrightHTMLA = "Copyright &#xA9; 2018 Kevin Bomberry. All Rights Reserved."
  CopyrightHTML = "Copyright &#xA9; 2018 Kevin Bomberry. All rights reserved. All other &copy;&nbsp;&#124;&nbsp;&reg;&nbsp;&#124;&nbsp;&trade; rights reserved by original holders respectivly."
  TwitterUser = "bomberry"

  includeFileInfo = false
  includeHugoMeta = false
# [permalinks]
# 	page = "/:title/"
# 	about = "/:filename/"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[menu]
  # [[menu.main]]
  #   identifier = "news"
  #   name = "news"
  #   pre = "<i class='fa fa-bullhorn'></i>"
  #   url = "/news/"
  #   weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    pre = "<span class='fa fa-address-card'>"
    post = "</span>"
    url = "/resume/"
    weight = 20
    hidden = false

  [[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    pre = "<i class='fa fa-barcode'> </i>"
    url = "/portfolio/"
    weight = 40
    hidden = false

#  [[menu.main]]
#    identifier = "kitchen"
#    name = "kitchen"
#    pre = "<i class='fa fa-coffee'> </i>"
#    url = "/kitchen/"
#    weight = 60
#    hidden = false

  # [[menu.main]]
  #   identifier = "1"
  #   name = "1"
  #   pre = "<i class='fa fa-heart'></i>"
  #   url = "/1/"
  #   weight = 80
  #   hidden = true

  # [[menu.main]]
  #   identifier = "projects"
  #   name = "projects"
  #   pre = "<i class='fa fa-paint-brush'></i>"
  #   url = "/projects/"
  #   weight = 100
  #   hidden = false

  # [[menu.main]]
  #   identifier = "contact"
  #   name = "contact"
  #   pre = "<i class='fa fa-bullhorn'></i>"
  #   url = "/contact/"
  #   weight = 120
  #   hidden = true

  # [[menu.main]]
  #   identifier = "adobe"
  #   name = "adobe"
  #   pre = "<i class='fa fa-'>A </i>"
  #   url = "/adobe/"
  #   weight = 140
  #   hidden = true

  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   url = "/posts"
  #   weight = 3

  [[menu.resume]]
    name = "Introduction"
    url = "#introduction"
    weight = 20

  [[menu.resume]]
    name = "Experience"
    url = "#experience"
    weight = 30

  [[menu.resume]]
    name = "Skills"
    url = "#skills"
    weight = 40

  [[menu.resume]]
    name = "Tools"
    url = "#tools"
    weight = 50

  [[menu.resume]]
    name = "Contact"
    url = "#contact"
    weight = 100



  [[menu.portfolio]]
    name = "Streamlio"
    url = "#streamlio"
    weight = 900


  [[menu.portfolio]]
    name = "CraftMaster"
    url = "#craftmaster"
    weight = 1000

  [[menu.portfolio]]
    name = "Auguste"
    url = "#adobe-august"
    weight = 1010

  [[menu.portfolio]]
    name = "Photoshop"
    url = "#adobe-photoshop"
    weight = 1020

  # [[menu.portfolio]]
  #   name = "Felix"
  #   url = "#felix"
  #   weight = 1030

  # [[menu.portfolio]]
  #   name = "Adobe"
  #   url = "#adobe"
  #   weight = 1040

  # [[menu.portfolio]]
  #   name = "Dimensions"
  #   url = "#dimensions"
  #   weight = 1050

  # [[menu.portfolio]]
  #   name = "Ps.com"
  #   url = "#PsCom"
  #   weight = 1060

  # [[menu.portfolio]]
  #   name = "PS Materials"
  #   url = "#materials"
  #   weight = 1070

  [[menu.portfolio]]
    name = "Able Pear"
    url = "#able-pear"
    weight = 1080

  # [[menu.portfolio]]
  #   name = "Artwork"
  #   url = "#artwork"
  #   weight = 1090


  # [[menu.casestudy_streamlio]]
  #   name = "introduction"
  #   url = "#bananas"
  #   weight = 1000
  #
  # [[menu.casestudy_streamlio]]
  #   name = "Challange"
  #   url = "#apples"
  #   weight = 1010
  #
  # [[menu.casestudy_streamlio]]
  #   name = "Process"
  #   url = "#apples"
  #   weight = 1020
  #
  # [[menu.casestudy_streamlio]]
  #   name = "Response"
  #   url = "#apples"
  #   weight = 1030
  #
  # [[menu.casestudy_streamlio]]
  #   name = "Conclusion"
  #   url = "#apples"
  #   weight = 1040


  [[menu.projects]]
    name = "Project ARIA"
    url = "#aria"
    weight = 1000

  [[menu.projects]]
    name = "Watch & Gears"
    url = "#watchAndGears"
    weight = 1010

  [[menu.projects]]
    name = "AppGraph Study"
    url = "#appGraph"
    weight = 1020

  [[menu.projects]]
    name = "Contextual UI"
    url = "#contextUI"
    weight = 1030





  [[menu.kitchen]]
    name = "Newsletter"
    url = "#newsletter"
    weight = 20

  [[menu.kitchen]]
    name = "Seasoning Salts"
    url = "#seasoningSalts"
    weight = 40

  [[menu.kitchen]]
    name = "Simple Syrups"
    url = "#simpleSyrup"
    weight = 60

  [[menu.kitchen]]
    name = "About"
    url = "#about"
    weight = 100




# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"







# Sitemap Variables
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
